import './globals.css'
import type { Metadata } from 'next'
import ThemeRegistry from './config/ThemeRegistry'
import ErrorBoundary from './components/ErrorBoundary'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body>
        <ErrorBoundary>
          <ThemeRegistry>{children}</ThemeRegistry>
        </ErrorBoundary>
      </body>
    </html>
  )
}
